### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by shanebo** [panoply/vscode-scss-style-tag#4]
@panoply, this plugin is exactly what I need. Thank you for building it, but I can't get it to work. Here's what I'm trying:

1. Install it
2. Create an html file
3. Add style tag with lang="scss"
4. write some scss
5. I'm seeing syntax errors with nested classes

Any ideas?

**Comment by panoply** [comment]
So the errors you're seeing is because the extension only supports syntax highlighting, and the HTML Language Server is treating the block of code as CSS not SCSS. The use case for this extension was project based and never used it beyond that. I can bring support for intellisense and diagnostics features to this extension but it would only fulfill such a small number of use cases. 

To avoid the validation, you can disable it within vscode workspace settings.

**Comment by shanebo** [comment]
Ah, I see. I'll try that. Thanks for the quick response.
